=== lilu09/XPDL_Compiler/src/xml/system.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.xpdl.com/system" xmlns:tns="http://www.xpdl.com/system" elementFormDefault="qualified">

    <element name="model" type="tns:model"></element>
    
    <complexType name="model">
    	<sequence>
    		<element name="component" type="tns:component_type"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="cpu" type="tns:cpu_type"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="gpu" type="tns:gpu_type"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="memory" type="tns:memory_type"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="software" type="tns:software_type"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="interconnect" type="tns:interconnect_type"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="library" type="tns:software_type" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="os" type="tns:software_type" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>

    </complexType>
    
    <complexType name="component_type">
    	<attribute name="type" type="string"></attribute>
    </complexType>

    <complexType name="cpu_type">
    	<attribute name="type" type="string"></attribute>
    	<attribute name="id" type="string"></attribute>
    </complexType>

    <complexType name="gpu_type">
    	<attribute name="type" type="string"></attribute>
    	<attribute name="id" type="string"></attribute>
    </complexType>

    <complexType name="memory_type">
    	<attribute name="type" type="string"></attribute>
    	<attribute name="id" type="string"></attribute>
    </complexType>

    <complexType name="software_type">
    	<attribute name="type" type="string"></attribute>
    	<attribute name="id" type="string"></attribute>
    </complexType>

    <complexType name="interconnect_type">
    	<attribute name="type" type="string"></attribute>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="head" type="string"></attribute>
    	<attribute name="tail" type="string"></attribute>
    </complexType>
</schema>

=== lilu09/XPDL_Compiler/example/system.xml
<?xml version="1.0" encoding="UTF-8"?>
<xpdl:model xmlns:xpdl="http://www.xpdl.com/system" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xpdl.com/system system.xsd">
	<xpdl:component type="system"/>
	<xpdl:cpu id="xpdl_cpu_0" type="Intel_Xeon_E5_2630L"/>
	<xpdl:cpu id="xpdl_cpu_1" type="Intel_Xeon_E5_2630L"/>
	<xpdl:gpu id="xpdl_gpu_0" type="Nvidia_K20c"/>
	<xpdl:gpu id="xpdl_gpu_1" type="Nvidia_K20c"/>
	<xpdl:memory id="xpdl_mem00" type="DDR3_8G" />
	<xpdl:memory id="xpdl_mem01" type="DDR3_16G" ></xpdl:memory>
	<xpdl:software id="xpdl_matlab" type="matlab"></xpdl:software>
	<xpdl:interconnect id="xpdl_interconnect" type="pcie3" head="xpdl_cpu_0" tail="xpdl_gpu_0" />
	<xpdl:library id="xpdl_blas" type="blas" />
	<xpdl:library id="xpdl_cublas" type="cublas" />
	<xpdl:os id="xpdl_ubuntu" type="ubuntu" />
</xpdl:model>
