=== lilu09/XPDL_Compiler/src/xml/xpdl_gpu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.xpdl.com/xpdl_gpu" xmlns:tns="http://www.xpdl.com/xpdl_gpu" elementFormDefault="qualified">

    <element name="model" type="tns:model_type"></element>
    
    <complexType name="model_type">
    	<sequence>
    		<element name="component" type="tns:component_type"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="gpu" type="tns:gpu_type"></element>
    	</sequence>
    </complexType>

    <complexType name="component_type">
    	<attribute name="type" type="string"></attribute>
    </complexType>

    <complexType name="gpu_type">
    	<sequence>
    		<element name="group" type="tns:group_type" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="memory" type="tns:memory_type" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="cache" type="tns:cache_type" maxOccurs="1"
    			minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="type" type="string"></attribute>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="programming_model" type="string"></attribute>
    	<attribute name="compiler" type="string"></attribute>
    	<attribute name="compute_capability" type="double"></attribute>
    	<attribute name="max_dim_thread_block_x" type="int"></attribute>
    	<attribute name="max_dim_thread_block_y" type="int"></attribute>
    	<attribute name="max_dim_thread_block_z" type="int"></attribute>
    	<attribute name="max_dim_grid_size_x" type="int"></attribute>
    	<attribute name="max_dim_grid_size_y" type="int"></attribute>
    	<attribute name="max_dim_grid_size_z" type="int"></attribute>
    	<attribute name="max_threads_per_block" type="int"></attribute>
    	<attribute name="num_of_cores" type="int"></attribute>
    </complexType>

    <complexType name="group_type">
    	<sequence>
    		<element name="group" type="tns:group_type"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="core" type="tns:core_type"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="memory" type="tns:memory_type"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="cache" type="tns:cache_type"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="quantity" type="string"></attribute>
    </complexType>

    <complexType name="core_type">
    	<attribute name="frequency" type="string"></attribute>
    	<attribute name="frequency_unit" type="string"></attribute>
    </complexType>

    <complexType name="memory_type">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="size" type="string"></attribute>
    	<attribute name="unit" type="string"></attribute>
    </complexType>

    <complexType name="cache_type">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="size" type="string"></attribute>
    	<attribute name="unit" type="string"></attribute>
    </complexType>

    <complexType name="programming_model_type">
    	<attribute name="NewAttribute" type="string"></attribute>
    </complexType>
</schema>

=== lilu09/XPDL_Compiler/src/xml/Nvidia_K20c.xml
<?xml version="1.0" encoding="UTF-8"?>
<xpdl:model xmlns:xpdl="http://www.xpdl.com/xpdl_gpu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xpdl.com/xpdl_gpu xpdl_gpu.xsd ">
  <xpdl:component type="nvidia_gpu" />
  <xpdl:gpu name="Nvidia_K20c" compute_capability="3.52"
  	max_dim_grid_size_x="2147483647" max_dim_grid_size_y="65535"
  	max_dim_grid_size_z="65535" max_dim_thread_block_x="1024"
  	max_dim_thread_block_y="1024" max_dim_thread_block_z="64"
  	max_threads_per_block="1024" type="nvidia_gpu" num_of_cores="2496">
  	<xpdl:group name="SMs" quantity="13">
  		<xpdl:group name="SM" quantity="192">
  			<xpdl:core frequency="0.706" frequency_unit="GHz"></xpdl:core>
  			<xpdl:memory name="Shared_per_block" size="49152"
  				unit="bytes" ></xpdl:memory>
  		</xpdl:group>
  		<xpdl:cache name="L1_per_SMs" size="64" unit="KiB"></xpdl:cache>
  	</xpdl:group>
  	<xpdl:memory name="Global" size="5120" unit="MiB"></xpdl:memory>
  	<xpdl:cache name="L2_shared" size="768" unit="KiB"></xpdl:cache>
  </xpdl:gpu>
</xpdl:model>
