=== lilu09/XPDL_Compiler/src/xml/xpdl_cpu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.xpdl.com/xpdl_cpu" xmlns:tns="http://www.xpdl.com/xpdl_cpu" elementFormDefault="qualified">

    <element name="model" type="tns:model_type"></element>
    
    <complexType name="model_type">
    	<sequence>
    		<element name="component" type="tns:component_type" maxOccurs="1" minOccurs="1"></element>
    		<element name="cpu" type="tns:cpu_type" maxOccurs="1" minOccurs="1"></element>

    	</sequence>
    </complexType>

    <complexType name="cpu_type">
    	<sequence>
    		<element name="group" type="tns:group_type"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="cache" type="tns:cache_type"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="core" type="tns:core_type"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="power_model" type="tns:power_model_type"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="type" type="string"></attribute>
    	<attribute name="num_of_cores" type="int"></attribute>
    	<attribute name="num_of_threads" type="int"></attribute>
    </complexType>

    <complexType name="group_type">
    	<sequence>
    		<element name="group" type="tns:group_type" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="core" type="tns:core_type" maxOccurs="unbounded" minOccurs="0"></element>
    		<element name="cache" type="tns:cache_type" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    	<attribute name="prefix" type="string"></attribute>
    	<attribute name="quantity" type="int"></attribute>
    </complexType>


    <complexType name="cache_type">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="size" type="int"></attribute>
    	<attribute name="unit" type="string"></attribute>
    	<attribute name="set" type="int"></attribute>
    </complexType>

    <complexType name="core_type">
    	<attribute name="frequency" type="double"></attribute>
    	<attribute name="unit" type="string"></attribute>
    </complexType>

    <complexType name="power_model_type">
    	<attribute name="type" type="string"></attribute>
    </complexType>

    <complexType name="component_type">
    	<attribute name="type" type="string"></attribute>
    </complexType>
</schema>

=== lilu09/XPDL_Compiler/src/xml/Intel_Xeon_E5_2630L.xml
<?xml version="1.0" encoding="UTF-8"?>
<xpdl:model xmlns:xpdl="http://www.xpdl.com/xpdl_cpu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xpdl.com/xpdl_cpu xpdl_cpu.xsd ">
  <xpdl:component type="cpu" />
  <xpdl:cpu name="Intel_Xeon_E5_2630L" num_of_cores="4"
  	num_of_threads="8">
  	<xpdl:group prefix="core_group" quantity="2">
  		<xpdl:group prefix="core_in_group" quantity="2">
  			<xpdl:core frequency="2" unit="GHz" />
  			<xpdl:cache name="L1" size="32" unit="KiB" set="4" />
  		</xpdl:group>
  		<xpdl:cache name="L2" size="256" unit="KiB" set="2" />
  	</xpdl:group>
  	<xpdl:cache name="L3" size="15" unit="MiB" set="1" />
  	<xpdl:power_model type="power_model_E5_2630L"></xpdl:power_model>
  </xpdl:cpu>
</xpdl:model>
